import type { INodeProperties } from 'n8n-workflow';

export const connectionDescription: INodeProperties[] = [
                {
			"displayName": "Operation",
			"name": "operation",
			"type": "options",
			"noDataExpression": true,
			"displayOptions": {
				"show": {
					"resource": [
						"Connection"
					]
				}
			},
			"options": [
				{
					"name": "Create Connection",
					"value": "Create Connection",
					"action": "Create a connection between a source and a destination",
					"description": "Create a connection between a source and a destination",
					"routing": {
						"request": {
							"method": "POST",
							"url": "=/v1/connections/create"
						}
					}
				},
				{
					"name": "Delete Connection",
					"value": "Delete Connection",
					"action": "Delete a connection",
					"description": "Delete a connection",
					"routing": {
						"request": {
							"method": "POST",
							"url": "=/v1/connections/delete"
						}
					}
				},
				{
					"name": "Get Connection",
					"value": "Get Connection",
					"action": "Get a connection",
					"description": "Get a connection",
					"routing": {
						"request": {
							"method": "POST",
							"url": "=/v1/connections/get"
						}
					}
				},
				{
					"name": "List Connections For Workspace",
					"value": "List Connections For Workspace",
					"action": "Returns all connections for a workspace.",
					"description": "List connections for workspace. Does not return deleted connections.",
					"routing": {
						"request": {
							"method": "POST",
							"url": "=/v1/connections/list"
						}
					}
				},
				{
					"name": "List All Connections For Workspace",
					"value": "List All Connections For Workspace",
					"action": "Returns all connections for a workspace, including deleted connections.",
					"description": "List connections for workspace, including deleted connections.",
					"routing": {
						"request": {
							"method": "POST",
							"url": "=/v1/connections/list_all"
						}
					}
				},
				{
					"name": "Reset Connection",
					"value": "Reset Connection",
					"action": "Reset the data for the connection. Deletes data generated by the connection in the destination. Resets any cursors back to initial state.",
					"description": "Reset the data for the connection. Deletes data generated by the connection in the destination. Resets any cursors back to initial state.",
					"routing": {
						"request": {
							"method": "POST",
							"url": "=/v1/connections/reset"
						}
					}
				},
				{
					"name": "Search Connections",
					"value": "Search Connections",
					"action": "Search connections",
					"description": "Search connections",
					"routing": {
						"request": {
							"method": "POST",
							"url": "=/v1/connections/search"
						}
					}
				},
				{
					"name": "Sync Connection",
					"value": "Sync Connection",
					"action": "Trigger a manual sync of the connection",
					"description": "Trigger a manual sync of the connection",
					"routing": {
						"request": {
							"method": "POST",
							"url": "=/v1/connections/sync"
						}
					}
				},
				{
					"name": "Update Connection",
					"value": "Update Connection",
					"action": "Update a connection",
					"description": "Apply a patch-style update to a connection. Only fields present on the update request body will be updated.\nNote that if a catalog is present in the request body, the connection's entire catalog will be replaced\nwith the catalog from the request. This means that to modify a single stream, the entire new catalog\ncontaining the updated stream needs to be sent.\n",
					"routing": {
						"request": {
							"method": "POST",
							"url": "=/v1/connections/update"
						}
					}
				}
			],
			"default": ""
		},
		{
			"displayName": "POST /v1/connections/create",
			"name": "operation",
			"type": "notice",
			"typeOptions": {
				"theme": "info"
			},
			"default": "",
			"displayOptions": {
				"show": {
					"resource": [
						"Connection"
					],
					"operation": [
						"Create Connection"
					]
				}
			}
		},
		{
			"required": true,
			"displayName": "Destination ID",
			"name": "destinationId",
			"type": "string",
			"default": "",
			"routing": {
				"send": {
					"property": "destinationId",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Connection"
					],
					"operation": [
						"Create Connection"
					]
				}
			}
		},
		{
			"displayName": "Geography",
			"name": "geography",
			"type": "options",
			"default": "auto",
			"options": [
				{
					"name": "Auto",
					"value": "auto"
				},
				{
					"name": "Us",
					"value": "us"
				},
				{
					"name": "Eu",
					"value": "eu"
				}
			],
			"routing": {
				"send": {
					"property": "geography",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Connection"
					],
					"operation": [
						"Create Connection"
					]
				}
			}
		},
		{
			"displayName": "Name",
			"name": "name",
			"type": "string",
			"default": "",
			"description": "Optional name of the connection",
			"routing": {
				"send": {
					"property": "name",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Connection"
					],
					"operation": [
						"Create Connection"
					]
				}
			}
		},
		{
			"displayName": "Namespace Definition",
			"name": "namespaceDefinition",
			"type": "options",
			"default": "source",
			"description": "Method used for computing final namespace in destination",
			"options": [
				{
					"name": "Source",
					"value": "source"
				},
				{
					"name": "Destination",
					"value": "destination"
				},
				{
					"name": "Customformat",
					"value": "customformat"
				}
			],
			"routing": {
				"send": {
					"property": "namespaceDefinition",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Connection"
					],
					"operation": [
						"Create Connection"
					]
				}
			}
		},
		{
			"displayName": "Namespace Format",
			"name": "namespaceFormat",
			"type": "string",
			"default": "${SOURCE_NAMESPACE}",
			"description": "Used when namespaceDefinition is 'customformat'. If blank then behaves like namespaceDefinition = 'destination'. If \"${SOURCE_NAMESPACE}\" then behaves like namespaceDefinition = 'source'.",
			"routing": {
				"send": {
					"property": "namespaceFormat",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Connection"
					],
					"operation": [
						"Create Connection"
					]
				}
			}
		},
		{
			"displayName": "Non Breaking Changes Preference",
			"name": "nonBreakingChangesPreference",
			"type": "options",
			"default": "ignore",
			"options": [
				{
					"name": "Ignore",
					"value": "ignore"
				},
				{
					"name": "Disable",
					"value": "disable"
				}
			],
			"routing": {
				"send": {
					"property": "nonBreakingChangesPreference",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Connection"
					],
					"operation": [
						"Create Connection"
					]
				}
			}
		},
		{
			"displayName": "Notify Schema Changes",
			"name": "notifySchemaChanges",
			"type": "boolean",
			"default": true,
			"routing": {
				"send": {
					"property": "notifySchemaChanges",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Connection"
					],
					"operation": [
						"Create Connection"
					]
				}
			}
		},
		{
			"displayName": "Operation Ids",
			"name": "operationIds",
			"type": "json",
			"default": "[\n  null\n]",
			"routing": {
				"send": {
					"property": "operationIds",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ JSON.parse($value) }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Connection"
					],
					"operation": [
						"Create Connection"
					]
				}
			}
		},
		{
			"displayName": "Prefix",
			"name": "prefix",
			"type": "string",
			"default": "",
			"description": "Prefix that will be prepended to the name of each stream when it is written to the destination.",
			"routing": {
				"send": {
					"property": "prefix",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Connection"
					],
					"operation": [
						"Create Connection"
					]
				}
			}
		},
		{
			"displayName": "Resource Requirements",
			"name": "resourceRequirements",
			"type": "json",
			"default": "{}",
			"description": "optional resource requirements to run workers (blank for unbounded allocations)",
			"routing": {
				"send": {
					"property": "resourceRequirements",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ JSON.parse($value) }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Connection"
					],
					"operation": [
						"Create Connection"
					]
				}
			}
		},
		{
			"displayName": "Schedule",
			"name": "schedule",
			"type": "json",
			"default": "{}",
			"description": "if null, then no schedule is set.",
			"routing": {
				"send": {
					"property": "schedule",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ JSON.parse($value) }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Connection"
					],
					"operation": [
						"Create Connection"
					]
				}
			}
		},
		{
			"displayName": "Schedule Data",
			"name": "scheduleData",
			"type": "json",
			"default": "{\n  \"basicSchedule\": {},\n  \"cron\": {}\n}",
			"description": "schedule for when the the connection should run, per the schedule type",
			"routing": {
				"send": {
					"property": "scheduleData",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ JSON.parse($value) }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Connection"
					],
					"operation": [
						"Create Connection"
					]
				}
			}
		},
		{
			"displayName": "Schedule Type",
			"name": "scheduleType",
			"type": "options",
			"default": "manual",
			"description": "determine how the schedule data should be interpreted",
			"options": [
				{
					"name": "Manual",
					"value": "manual"
				},
				{
					"name": "Basic",
					"value": "basic"
				},
				{
					"name": "Cron",
					"value": "cron"
				}
			],
			"routing": {
				"send": {
					"property": "scheduleType",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Connection"
					],
					"operation": [
						"Create Connection"
					]
				}
			}
		},
		{
			"displayName": "Source Catalog ID",
			"name": "sourceCatalogId",
			"type": "string",
			"default": "",
			"routing": {
				"send": {
					"property": "sourceCatalogId",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Connection"
					],
					"operation": [
						"Create Connection"
					]
				}
			}
		},
		{
			"required": true,
			"displayName": "Source ID",
			"name": "sourceId",
			"type": "string",
			"default": "",
			"routing": {
				"send": {
					"property": "sourceId",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Connection"
					],
					"operation": [
						"Create Connection"
					]
				}
			}
		},
		{
			"required": true,
			"displayName": "Status",
			"name": "status",
			"type": "options",
			"default": "active",
			"description": "Active means that data is flowing through the connection. Inactive means it is not. Deprecated means the connection is off and cannot be re-activated. the schema field describes the elements of the schema that will be synced.",
			"options": [
				{
					"name": "Active",
					"value": "active"
				},
				{
					"name": "Inactive",
					"value": "inactive"
				},
				{
					"name": "Deprecated",
					"value": "deprecated"
				}
			],
			"routing": {
				"send": {
					"property": "status",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Connection"
					],
					"operation": [
						"Create Connection"
					]
				}
			}
		},
		{
			"displayName": "Sync Catalog",
			"name": "syncCatalog",
			"type": "json",
			"default": "{\n  \"streams\": [\n    {\n      \"config\": {\n        \"cursorField\": [\n          null\n        ],\n        \"primaryKey\": [\n          [\n            null\n          ]\n        ],\n        \"selectedFields\": [\n          {\n            \"fieldPath\": [\n              null\n            ]\n          }\n        ]\n      },\n      \"stream\": {\n        \"defaultCursorField\": [\n          null\n        ],\n        \"sourceDefinedPrimaryKey\": [\n          [\n            null\n          ]\n        ],\n        \"supportedSyncModes\": [\n          {}\n        ]\n      }\n    }\n  ]\n}",
			"description": "describes the available schema (catalog).",
			"routing": {
				"send": {
					"property": "syncCatalog",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ JSON.parse($value) }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Connection"
					],
					"operation": [
						"Create Connection"
					]
				}
			}
		},
		{
			"displayName": "POST /v1/connections/delete",
			"name": "operation",
			"type": "notice",
			"typeOptions": {
				"theme": "info"
			},
			"default": "",
			"displayOptions": {
				"show": {
					"resource": [
						"Connection"
					],
					"operation": [
						"Delete Connection"
					]
				}
			}
		},
		{
			"required": true,
			"displayName": "Connection ID",
			"name": "connectionId",
			"type": "string",
			"default": "",
			"routing": {
				"send": {
					"property": "connectionId",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Connection"
					],
					"operation": [
						"Delete Connection"
					]
				}
			}
		},
		{
			"displayName": "POST /v1/connections/get",
			"name": "operation",
			"type": "notice",
			"typeOptions": {
				"theme": "info"
			},
			"default": "",
			"displayOptions": {
				"show": {
					"resource": [
						"Connection"
					],
					"operation": [
						"Get Connection"
					]
				}
			}
		},
		{
			"required": true,
			"displayName": "Connection ID",
			"name": "connectionId",
			"type": "string",
			"default": "",
			"routing": {
				"send": {
					"property": "connectionId",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Connection"
					],
					"operation": [
						"Get Connection"
					]
				}
			}
		},
		{
			"displayName": "POST /v1/connections/list",
			"name": "operation",
			"type": "notice",
			"typeOptions": {
				"theme": "info"
			},
			"default": "",
			"displayOptions": {
				"show": {
					"resource": [
						"Connection"
					],
					"operation": [
						"List Connections For Workspace"
					]
				}
			}
		},
		{
			"required": true,
			"displayName": "Workspace ID",
			"name": "workspaceId",
			"type": "string",
			"default": "",
			"routing": {
				"send": {
					"property": "workspaceId",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Connection"
					],
					"operation": [
						"List Connections For Workspace"
					]
				}
			}
		},
		{
			"displayName": "POST /v1/connections/list_all",
			"name": "operation",
			"type": "notice",
			"typeOptions": {
				"theme": "info"
			},
			"default": "",
			"displayOptions": {
				"show": {
					"resource": [
						"Connection"
					],
					"operation": [
						"List All Connections For Workspace"
					]
				}
			}
		},
		{
			"required": true,
			"displayName": "Workspace ID",
			"name": "workspaceId",
			"type": "string",
			"default": "",
			"routing": {
				"send": {
					"property": "workspaceId",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Connection"
					],
					"operation": [
						"List All Connections For Workspace"
					]
				}
			}
		},
		{
			"displayName": "POST /v1/connections/reset",
			"name": "operation",
			"type": "notice",
			"typeOptions": {
				"theme": "info"
			},
			"default": "",
			"displayOptions": {
				"show": {
					"resource": [
						"Connection"
					],
					"operation": [
						"Reset Connection"
					]
				}
			}
		},
		{
			"required": true,
			"displayName": "Connection ID",
			"name": "connectionId",
			"type": "string",
			"default": "",
			"routing": {
				"send": {
					"property": "connectionId",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Connection"
					],
					"operation": [
						"Reset Connection"
					]
				}
			}
		},
		{
			"displayName": "POST /v1/connections/search",
			"name": "operation",
			"type": "notice",
			"typeOptions": {
				"theme": "info"
			},
			"default": "",
			"displayOptions": {
				"show": {
					"resource": [
						"Connection"
					],
					"operation": [
						"Search Connections"
					]
				}
			}
		},
		{
			"displayName": "Connection ID",
			"name": "connectionId",
			"type": "string",
			"default": "",
			"routing": {
				"send": {
					"property": "connectionId",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Connection"
					],
					"operation": [
						"Search Connections"
					]
				}
			}
		},
		{
			"displayName": "Destination",
			"name": "destination",
			"type": "json",
			"default": "{\n  \"connectionConfiguration\": {\n    \"user\": \"charles\"\n  }\n}",
			"routing": {
				"send": {
					"property": "destination",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ JSON.parse($value) }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Connection"
					],
					"operation": [
						"Search Connections"
					]
				}
			}
		},
		{
			"displayName": "Destination ID",
			"name": "destinationId",
			"type": "string",
			"default": "",
			"routing": {
				"send": {
					"property": "destinationId",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Connection"
					],
					"operation": [
						"Search Connections"
					]
				}
			}
		},
		{
			"displayName": "Name",
			"name": "name",
			"type": "string",
			"default": "",
			"routing": {
				"send": {
					"property": "name",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Connection"
					],
					"operation": [
						"Search Connections"
					]
				}
			}
		},
		{
			"displayName": "Namespace Definition",
			"name": "namespaceDefinition",
			"type": "options",
			"default": "source",
			"description": "Method used for computing final namespace in destination",
			"options": [
				{
					"name": "Source",
					"value": "source"
				},
				{
					"name": "Destination",
					"value": "destination"
				},
				{
					"name": "Customformat",
					"value": "customformat"
				}
			],
			"routing": {
				"send": {
					"property": "namespaceDefinition",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Connection"
					],
					"operation": [
						"Search Connections"
					]
				}
			}
		},
		{
			"displayName": "Namespace Format",
			"name": "namespaceFormat",
			"type": "string",
			"default": "${SOURCE_NAMESPACE}",
			"description": "Used when namespaceDefinition is 'customformat'. If blank then behaves like namespaceDefinition = 'destination'. If \"${SOURCE_NAMESPACE}\" then behaves like namespaceDefinition = 'source'.",
			"routing": {
				"send": {
					"property": "namespaceFormat",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Connection"
					],
					"operation": [
						"Search Connections"
					]
				}
			}
		},
		{
			"displayName": "Prefix",
			"name": "prefix",
			"type": "string",
			"default": "",
			"description": "Prefix that will be prepended to the name of each stream when it is written to the destination.",
			"routing": {
				"send": {
					"property": "prefix",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Connection"
					],
					"operation": [
						"Search Connections"
					]
				}
			}
		},
		{
			"displayName": "Schedule",
			"name": "schedule",
			"type": "json",
			"default": "{}",
			"description": "if null, then no schedule is set.",
			"routing": {
				"send": {
					"property": "schedule",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ JSON.parse($value) }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Connection"
					],
					"operation": [
						"Search Connections"
					]
				}
			}
		},
		{
			"displayName": "Schedule Data",
			"name": "scheduleData",
			"type": "json",
			"default": "{\n  \"basicSchedule\": {},\n  \"cron\": {}\n}",
			"description": "schedule for when the the connection should run, per the schedule type",
			"routing": {
				"send": {
					"property": "scheduleData",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ JSON.parse($value) }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Connection"
					],
					"operation": [
						"Search Connections"
					]
				}
			}
		},
		{
			"displayName": "Schedule Type",
			"name": "scheduleType",
			"type": "options",
			"default": "manual",
			"description": "determine how the schedule data should be interpreted",
			"options": [
				{
					"name": "Manual",
					"value": "manual"
				},
				{
					"name": "Basic",
					"value": "basic"
				},
				{
					"name": "Cron",
					"value": "cron"
				}
			],
			"routing": {
				"send": {
					"property": "scheduleType",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Connection"
					],
					"operation": [
						"Search Connections"
					]
				}
			}
		},
		{
			"displayName": "Source",
			"name": "source",
			"type": "json",
			"default": "{\n  \"connectionConfiguration\": {\n    \"user\": \"charles\"\n  }\n}",
			"routing": {
				"send": {
					"property": "source",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ JSON.parse($value) }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Connection"
					],
					"operation": [
						"Search Connections"
					]
				}
			}
		},
		{
			"displayName": "Source ID",
			"name": "sourceId",
			"type": "string",
			"default": "",
			"routing": {
				"send": {
					"property": "sourceId",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Connection"
					],
					"operation": [
						"Search Connections"
					]
				}
			}
		},
		{
			"displayName": "Status",
			"name": "status",
			"type": "options",
			"default": "active",
			"description": "Active means that data is flowing through the connection. Inactive means it is not. Deprecated means the connection is off and cannot be re-activated. the schema field describes the elements of the schema that will be synced.",
			"options": [
				{
					"name": "Active",
					"value": "active"
				},
				{
					"name": "Inactive",
					"value": "inactive"
				},
				{
					"name": "Deprecated",
					"value": "deprecated"
				}
			],
			"routing": {
				"send": {
					"property": "status",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Connection"
					],
					"operation": [
						"Search Connections"
					]
				}
			}
		},
		{
			"displayName": "POST /v1/connections/sync",
			"name": "operation",
			"type": "notice",
			"typeOptions": {
				"theme": "info"
			},
			"default": "",
			"displayOptions": {
				"show": {
					"resource": [
						"Connection"
					],
					"operation": [
						"Sync Connection"
					]
				}
			}
		},
		{
			"required": true,
			"displayName": "Connection ID",
			"name": "connectionId",
			"type": "string",
			"default": "",
			"routing": {
				"send": {
					"property": "connectionId",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Connection"
					],
					"operation": [
						"Sync Connection"
					]
				}
			}
		},
		{
			"displayName": "POST /v1/connections/update",
			"name": "operation",
			"type": "notice",
			"typeOptions": {
				"theme": "info"
			},
			"default": "",
			"displayOptions": {
				"show": {
					"resource": [
						"Connection"
					],
					"operation": [
						"Update Connection"
					]
				}
			}
		},
		{
			"displayName": "Breaking Change",
			"name": "breakingChange",
			"type": "boolean",
			"default": true,
			"routing": {
				"send": {
					"property": "breakingChange",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Connection"
					],
					"operation": [
						"Update Connection"
					]
				}
			}
		},
		{
			"required": true,
			"displayName": "Connection ID",
			"name": "connectionId",
			"type": "string",
			"default": "",
			"routing": {
				"send": {
					"property": "connectionId",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Connection"
					],
					"operation": [
						"Update Connection"
					]
				}
			}
		},
		{
			"displayName": "Geography",
			"name": "geography",
			"type": "options",
			"default": "auto",
			"options": [
				{
					"name": "Auto",
					"value": "auto"
				},
				{
					"name": "Us",
					"value": "us"
				},
				{
					"name": "Eu",
					"value": "eu"
				}
			],
			"routing": {
				"send": {
					"property": "geography",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Connection"
					],
					"operation": [
						"Update Connection"
					]
				}
			}
		},
		{
			"displayName": "Name",
			"name": "name",
			"type": "string",
			"default": "",
			"description": "Name that will be set to this connection",
			"routing": {
				"send": {
					"property": "name",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Connection"
					],
					"operation": [
						"Update Connection"
					]
				}
			}
		},
		{
			"displayName": "Namespace Definition",
			"name": "namespaceDefinition",
			"type": "options",
			"default": "source",
			"description": "Method used for computing final namespace in destination",
			"options": [
				{
					"name": "Source",
					"value": "source"
				},
				{
					"name": "Destination",
					"value": "destination"
				},
				{
					"name": "Customformat",
					"value": "customformat"
				}
			],
			"routing": {
				"send": {
					"property": "namespaceDefinition",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Connection"
					],
					"operation": [
						"Update Connection"
					]
				}
			}
		},
		{
			"displayName": "Namespace Format",
			"name": "namespaceFormat",
			"type": "string",
			"default": "${SOURCE_NAMESPACE}",
			"description": "Used when namespaceDefinition is 'customformat'. If blank then behaves like namespaceDefinition = 'destination'. If \"${SOURCE_NAMESPACE}\" then behaves like namespaceDefinition = 'source'.",
			"routing": {
				"send": {
					"property": "namespaceFormat",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Connection"
					],
					"operation": [
						"Update Connection"
					]
				}
			}
		},
		{
			"displayName": "Non Breaking Changes Preference",
			"name": "nonBreakingChangesPreference",
			"type": "options",
			"default": "ignore",
			"options": [
				{
					"name": "Ignore",
					"value": "ignore"
				},
				{
					"name": "Disable",
					"value": "disable"
				}
			],
			"routing": {
				"send": {
					"property": "nonBreakingChangesPreference",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Connection"
					],
					"operation": [
						"Update Connection"
					]
				}
			}
		},
		{
			"displayName": "Notify Schema Changes",
			"name": "notifySchemaChanges",
			"type": "boolean",
			"default": true,
			"routing": {
				"send": {
					"property": "notifySchemaChanges",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Connection"
					],
					"operation": [
						"Update Connection"
					]
				}
			}
		},
		{
			"displayName": "Operation Ids",
			"name": "operationIds",
			"type": "json",
			"default": "[\n  null\n]",
			"routing": {
				"send": {
					"property": "operationIds",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ JSON.parse($value) }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Connection"
					],
					"operation": [
						"Update Connection"
					]
				}
			}
		},
		{
			"displayName": "Prefix",
			"name": "prefix",
			"type": "string",
			"default": "",
			"description": "Prefix that will be prepended to the name of each stream when it is written to the destination.",
			"routing": {
				"send": {
					"property": "prefix",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Connection"
					],
					"operation": [
						"Update Connection"
					]
				}
			}
		},
		{
			"displayName": "Resource Requirements",
			"name": "resourceRequirements",
			"type": "json",
			"default": "{}",
			"description": "optional resource requirements to run workers (blank for unbounded allocations)",
			"routing": {
				"send": {
					"property": "resourceRequirements",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ JSON.parse($value) }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Connection"
					],
					"operation": [
						"Update Connection"
					]
				}
			}
		},
		{
			"displayName": "Schedule",
			"name": "schedule",
			"type": "json",
			"default": "{}",
			"description": "if null, then no schedule is set.",
			"routing": {
				"send": {
					"property": "schedule",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ JSON.parse($value) }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Connection"
					],
					"operation": [
						"Update Connection"
					]
				}
			}
		},
		{
			"displayName": "Schedule Data",
			"name": "scheduleData",
			"type": "json",
			"default": "{\n  \"basicSchedule\": {},\n  \"cron\": {}\n}",
			"description": "schedule for when the the connection should run, per the schedule type",
			"routing": {
				"send": {
					"property": "scheduleData",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ JSON.parse($value) }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Connection"
					],
					"operation": [
						"Update Connection"
					]
				}
			}
		},
		{
			"displayName": "Schedule Type",
			"name": "scheduleType",
			"type": "options",
			"default": "manual",
			"description": "determine how the schedule data should be interpreted",
			"options": [
				{
					"name": "Manual",
					"value": "manual"
				},
				{
					"name": "Basic",
					"value": "basic"
				},
				{
					"name": "Cron",
					"value": "cron"
				}
			],
			"routing": {
				"send": {
					"property": "scheduleType",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Connection"
					],
					"operation": [
						"Update Connection"
					]
				}
			}
		},
		{
			"displayName": "Source Catalog ID",
			"name": "sourceCatalogId",
			"type": "string",
			"default": "",
			"routing": {
				"send": {
					"property": "sourceCatalogId",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Connection"
					],
					"operation": [
						"Update Connection"
					]
				}
			}
		},
		{
			"displayName": "Status",
			"name": "status",
			"type": "options",
			"default": "active",
			"description": "Active means that data is flowing through the connection. Inactive means it is not. Deprecated means the connection is off and cannot be re-activated. the schema field describes the elements of the schema that will be synced.",
			"options": [
				{
					"name": "Active",
					"value": "active"
				},
				{
					"name": "Inactive",
					"value": "inactive"
				},
				{
					"name": "Deprecated",
					"value": "deprecated"
				}
			],
			"routing": {
				"send": {
					"property": "status",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Connection"
					],
					"operation": [
						"Update Connection"
					]
				}
			}
		},
		{
			"displayName": "Sync Catalog",
			"name": "syncCatalog",
			"type": "json",
			"default": "{\n  \"streams\": [\n    {\n      \"config\": {\n        \"cursorField\": [\n          null\n        ],\n        \"primaryKey\": [\n          [\n            null\n          ]\n        ],\n        \"selectedFields\": [\n          {\n            \"fieldPath\": [\n              null\n            ]\n          }\n        ]\n      },\n      \"stream\": {\n        \"defaultCursorField\": [\n          null\n        ],\n        \"sourceDefinedPrimaryKey\": [\n          [\n            null\n          ]\n        ],\n        \"supportedSyncModes\": [\n          {}\n        ]\n      }\n    }\n  ]\n}",
			"description": "describes the available schema (catalog).",
			"routing": {
				"send": {
					"property": "syncCatalog",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ JSON.parse($value) }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Connection"
					],
					"operation": [
						"Update Connection"
					]
				}
			}
		},
];
